### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by karan** [puppetlabs/puppetlabs-windows#13]
Without a license, this project isn't open source and no one can use the code.

Please use something like http://choosealicense.com/ to decide what license to use. I recommend MIT or GPL.

**Comment by ferventcoder** [comment]
https://github.com/puppetlabs/puppetlabs-windows/blob/master/metadata.json#L6 ?

**Comment by ferventcoder** [comment]
Done. It's always Apache 2.0.
